stages:
  - integration
  - delivery
  - deploy

prod:
  stage: deploy
  script:
    - echo "TAG=latest" >> .build_info
    - echo "DOCKERFILE=Dockerfile.dev" >> .build_info
    - make build-image
    - make push-image
    - docker service update --with-registry-auth -d --image gitlab.abutech.uz:5050/najottalim.uz/new-nt-user-frontend/new-nt-user-frontend  nt_user-frontend-new
  only:
    - master
  tags:
    - nt_prod

# DEV ENVIRONMENT

build-image:
  stage: integration
  script:
    - echo "TAG=dev" >> .build_info
    - echo "DOCKERFILE=Dockerfile.dev" >> .build_info
    - make build-image
  only:
    - dev
  tags:
    - nt_dev

push-image:
  stage: delivery
  script:
    - echo "TAG=dev" >> .build_info
    - make push-image
  only:
    - dev
  tags:
    - nt_dev

update-service:
  stage: deploy
  script:
    - docker service update --with-registry-auth -d --image gitlab.abutech.uz:5050/najottalim.uz/new-nt-user-frontend/new-nt-user-frontend:dev  nt_user-frontend-new
  environment:
    name: development
    url: https://test.app.najottalim.uz/
  only:
    - dev
  tags:
    - nt_dev
